#!/usr/bin/env python
import os, glob
from os.path import join, exists
from fabricate import main, autoclean, run

BUILD = 'build'
GOLD = 'gold'

tests = glob.glob('*.circ')

def build():
    for test in tests:
        base, suffix = test.split('.')
        compile(base)

def compile(base):
    u = base+'.ucf'
    v = base+'.v'
    circ = base+'.circ'
    py = join(BUILD,base+'.py')
    buildu, goldu = join(BUILD,u), join(GOLD,u)
    buildv, goldv = join(BUILD,v), join(GOLD,v)
    run('python', 'logi.py', circ, py)
    run('python', py)
    if exists(goldu):
        run('cmp',buildu,goldu)
    if exists(goldv):
        run('cmp',buildv,goldv)

def clean():
    autoclean()

def gold():
    os.system('cp %s/* %s' % (BUILD, GOLD))

main()
